### PR TITLE
Avoid copying received message buffers

### PR DESCRIPTION
**Pull request by kkoopa**
Don't Copy That Floppy

### CODE REVIEW

**Comment by reqshark** [comment]
woah :pager: avoiding buffer copy?! SICK! 

 Thanks @kkoopa! :palm_tree:

btw what happened to travis on this one? whatever, I got `894 passing (10.1s)` on linux/osx..

**Comment by kkoopa** [comment]
Don't know what happened to Travis. I was wondering about it myself. Is it set up to test all PRs (the default)?

Out of curiosity, was there any speedup with the current (performance) tests?

**Comment by reqshark** [comment]
Indeed with the speedup, even on the smallest bufs we're getting a nice 10% bump in throughput.. 

### before:
```
message size: 1 [B]
message count: 100000
throughput: 81940 [msg/s]
throughput: 0.656 [Mb/s]
```

### after:
```
message size: 1 [B]
message count: 100000
throughput: 98185 [msg/s]
throughput: 0.785 [Mb/s]
```

And as for travis,

> Is it set up to test all PRs (the default)?

It's always been that way.. although looking at the yaml it does say [`branches: only master`](https://github.com/nickdesaulniers/node-nanomsg/blob/master/.travis.yml#L10-L12)

**Comment by reqshark** [comment]
yup, @travis-ci with the air ball! not even close to the rim...

hmm

**Comment by kkoopa** [comment]
That's actually a 20 % increase. Now the remaining overhead is just 2 %. Anyway, nice that it did some good.

**Comment by reqshark** [comment]
right, clearly a 20% increase in throughput there...

moreover, consistently improved performance across larger buffer ranges too

### before:
```sh
message size: 10 [B]
message count: 100000
throughput: 92122 [msg/s]
throughput: 7.37 [Mb/s]
```
### after:
```sh
message size: 10 [B]
message count: 100000
throughput: 117064 [msg/s]
throughput: 9.365 [Mb/s]
```

well done @kkoopa ! cheers! :beers:

**Comment by yoshuawuyts** [comment]
sick!

**Pull request merged**
