### PR TITLE
Update to NAN 2.0.8

### LINKED ISSUE #103: ecosystem upgrades
## relevant ecosystem changes

- [ ] nan 2

#### beta 6 targets: 
- [x] windows
- [x] linx
- [x] osx

In addition to beta 6, let's use recently overhauled [native abstractions](https://github.com/nodejs/nan/issues/376) to compile against API breakage upstream in V8 4.4.63.26... like if we want to use iojs3. no more Handle, it's Local now. 

btw, @nickdesaulniers, iojs3 brings changes to node::buffer that I think we need to take a look at 

last week I was having some problems just getting nan2 off the ground but [that was NPM related](https://github.com/nodejs/nan/issues/405). I'll take another swing at it as soon as I can. In the meantime, PRs on any of these are most welcome :)

### PR DESCRIPTION
**Pull request by kkoopa**
Fixes #103

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
wow! The PR in which @kkoopa basically rewrites the entire C++ part of this lib!  Thanks for the awesome PR.  The `FromJust` method name makes me cringe, but this looks good!  Let me verify the tests and merge!

**Comment by kkoopa** [comment]
It's easy when one wrote the binding layer in the first place. Besides, the logic remains unchained, only mechanical search and replace was needed. Took me around ten minutes.

`FromJust` is [standard V8 nomenclature](https://v8docs.nodesource.com/io.js-3.0/d9/d4b/classv8_1_1_maybe.html#ad97c01315c73bf49b522c2996638a2d2) and is named so since it is paired with [`FromMaybe`](https://v8docs.nodesource.com/io.js-3.0/d9/d4b/classv8_1_1_maybe.html#ab0d2cdc887e031a2f60eec7e248c05d7), which should be used when there is a chance of the value being empty.

**Comment by reqshark** [comment]
@kkoopa mahalo!

**Comment by nickdesaulniers** [comment]
[I understand the concept of Maybe](http://nickdesaulniers.github.io/blog/2013/05/07/rust-pattern-matching-and-the-option-type/), but what is `Just`?

**Comment by kkoopa** [comment]
It is just a value, that is, the opposite of nothing.

**Comment by reqshark** [comment]
BTW looks our latest module release `2.1.1` also works with `node v4.0.0`.

excellent work @kkoopa, thanks again.

**Pull request merged**
