### PR TITLE
upgrade libnanomsg Fixes #128, possibly #107

### LINKED ISSUE #128: update libnanomsg submodule
we need to checkout a more recent copy of the lib, especially as the ongoing work to better meet RFC standards is taking place upstream

see https://github.com/nanomsg/nanomsg/issues/489

### PR DESCRIPTION
**Pull request by nickdesaulniers**
review? @reqshark

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
`cd deps/nanomsg` then `git log 5515f96..3573033` or `git diff 5515f96..3573033` or `gitk 5515f96..3573033`

**Comment by reqshark** [comment]
this good we can merge this now but there might be more changes coming upstream

**Comment by reqshark** [comment]
wait, @nickdesaulniers can you add the `NN_RCVMAXSIZE` option in [index.js](https://github.com/nickdesaulniers/node-nanomsg/blob/master/lib/index.js#L366-L376) as well?

**Comment by reqshark** [comment]
or i guess we can add that option support later in a different PR and properly develop a test for it, especially if this is just about updating the submodule

**Comment by reqshark** [comment]
wow the compile noise got fixed on osx!

**Pull request merged**
