### PR TITLE
polyfill buffer.equals Fixes #82

### LINKED ISSUE #82: bad test case
The test send.js says this on Travis in Node 0.10:

/home/travis/build/nickdesaulniers/node-nanomsg/node_modules/tape/index.js:75
        throw err
              ^
TypeError: Object hello has no method 'equals'
    at Socket.<anonymous> (/home/travis/build/nickdesaulniers/node-nanomsg/test/send.js:87:17)
    at Socket.emit (events.js:95:17)
    at Socket._receive (/home/travis/build/nickdesaulniers/node-nanomsg/lib/index.js:184:10)
    at Socket.<anonymous> (/home/travis/build/nickdesaulniers/node-nanomsg/lib/index.js:198:30)

I'm pretty sure that's from this: https://github.com/nickdesaulniers/node-nanomsg/blob/master/test/send.js#L87 when I removed should.

### PR DESCRIPTION
**Pull request by nickdesaulniers**
review? @reqshark

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
do you think we should throw in case Buffer.prototype.equals is not defined, to prevent people from arbitrarily removing the polyfill?

**Comment by reqshark** [comment]
> arbitrarily removing the polyfill

it seems extremely unlikely. how would that even happen when it's just a dep for the test?

I'm thinking: isn't `require('buffer-equals-polyfill')`, according to the node require algorithm getting called long after `Buffer` class/prototype?

**Comment by reqshark** [comment]
is [this the github repo](https://github.com/davidmarkclements/buffer-equals-polyfill) for it?

**Comment by nickdesaulniers** [comment]
yeah

**Comment by reqshark** [comment]
eh, i wouldn't worry about that happening, because even if that could happen I think it falls back to some comparative logic in here: https://github.com/soldair/node-buffer-compare, which looks fine to me

**Comment by reqshark** [comment]
hey this is a great fix for that test when using node 0.10!

**Comment by reqshark** [comment]
sizzurp f08bdd09aee5ebafe1afbc98f231c70866fdcc04!

**Pull request merged**
