### PR TITLE
give better form to term test

### LINKED ISSUE #119: bad form in tests/standalone
`term()` test:

https://github.com/nickdesaulniers/node-nanomsg/blob/master/test/standalone/term.js

not sure what error gets tested. we're just seding or awking there without calling bind or connect.

### PR DESCRIPTION
**Pull request by reqshark**
fixes #119

### CODE REVIEW

**Comment by reqshark** [comment]
@nickdesaulniers, or @tcr, please review

**Comment by reqshark** [comment]
got another timeout :hourglass: reiterating importance of #114 

https://travis-ci.org/nickdesaulniers/node-nanomsg/jobs/80297456

**Comment by nickdesaulniers** [comment]
arg why do tables have to have a header?! :point_down: :house_with_garden: :fire: :oncoming_police_car:

**Comment by nickdesaulniers** [comment]
oops wrong thread :jack_o_lantern: :japan: :japanese_goblin:

**Comment by reqshark** [comment]
it's green :game_die:

**Comment by nickdesaulniers** [comment]
all of the tests will need reformatting, eventually.  Not a priority though

**Pull request merged**
