### PR TITLE
depend on custom nanomsg with backported patch Fixes #50

### LINKED ISSUE #50: NN_RCVPRIO symbol not exported
this is an issue with the `nn` binding in our javascript.

for the new `rcvprio` option function, we're having to go: 

```js
/**
 * generic socket-level NN_SOL_SOCKET options
 */
var sol = {
  linger          : nn.NN_LINGER,
  sndbuf          : nn.NN_SNDBUF,
  rcvbuf          : nn.NN_RCVBUF,
  sndtimeo        : nn.NN_SNDTIMEO,
  rcvtimeo        : nn.NN_RCVTIMEO,
  reconn          : nn.NN_RECONNECT_IVL,
  maxreconn       : nn.NN_RECONNECT_IVL_MAX,
  sndprio         : nn.NN_SNDPRIO,
  rcvprio         : 9,
  tcpnodelay      : nn.NN_TCP_NODELAY,
}
```

### PR DESCRIPTION
**Pull request by nickdesaulniers**
review? @reqshark 

check this out and run the tests, there seems to be even more breakage...

### CODE REVIEW

**Comment by reqshark** [comment]
Passes on linux and osx, was there windows breakage?

**Comment by reqshark** [comment]
LGTM, this branch just needs to rebase off master (fetch the perf commit) before we can merge

**Comment by nickdesaulniers** [comment]
try running `node test/symbolinfo.js` (2 errors) and `node test/symbol.js` (1 error)

**Comment by nickdesaulniers** [comment]
Calling `require('nanomsg').symbol(93)` seems to be throwing an `[Error: Invalid argument]`.

**Comment by nickdesaulniers** [comment]
but symbols.length seems to be 94

**Comment by reqshark** [comment]
you're re-cloning and still getting that?

```bash
$ git clone https://github.com/nickdesaulniers/node-nanomsg.git n && cd n && git checkout nn_rcvprio
$ git submodule update --init
Submodule path 'deps/nanomsg': checked out 'e046874531d937e94d0cde01910e2250a601bbc6'
$ npm i
$ node test/symbol.js
1..188
# tests 188
# pass  188

# ok

$ node test/symbolinfo.js
1..470
# tests 470
# pass  470

# ok
```

**Comment by nickdesaulniers** [comment]
hmm...something fishy is going on.  I'm on OSX, you?

**Comment by reqshark** [comment]
same

**Comment by nickdesaulniers** [comment]
It also looks like `nano.symbol(X)` is not returning the same values as `symbols.symbols[X]`

**Comment by nickdesaulniers** [comment]
forgot a npm install. dipshit

**Comment by reqshark** [comment]
then lets stop using `nn_symbol()` the, it seems borked.

let's just do the regular export constant.

besides you're still going to need do another PR on nanomsg if we decide to support msg_control stuff and the recent ancillary data updates that sustrik made as part of the beta 4 release:

```c
PROTO_SP
SP_HDR
```

Those symbols dont even have the `NN_` prefix, anyway I wouldn't be surprised if  `nn_symbol()` needs upstream patchwork for those too.

**Comment by reqshark** [comment]
nvm

**Pull request merged**
